### ISSUE TITLE
Works in reverse for task

### ISSUE THREAD

**Issue by robertandrews** [shap-po/obsidian-party#2]
The confetti appears when the task is UN-checked...

https://user-images.githubusercontent.com/3158787/193531549-b9911355-5303-4efd-a1c0-3e4027ca5b60.mov

**Comment by shap-po** [comment]
Thanks for reporting

**Comment by shap-po** [comment]
Do you have any plugins/themes that modify checkboxes?
Can you please send an HTML code of this checkbox in both checked and unchecked states?
(select element in the Elements panel and click on the copy -> copy outerHTML)
It should look like this:
unchecked: `<input class="task-list-item-checkbox" type="checkbox" data-task=" ">`
checked: `<input class="task-list-item-checkbox" type="checkbox" data-task="x">`

**Comment by robertandrews** [comment]
Active plugins are:

- Admonition
- Linter
- Party
- Paste URL into selection
- Raindrop Highlights
- Simple Embeds
- Style Settings
- Tasks

Actually, I've just come back to this, turned off everything except Party and Tasks, and it now doesn't work at all in either direction.

BTW, this is Obsidian 0.16.3 Insider, which I should have said.
