### ISSUE TITLE
Option for effects to work only on checkboxes from Tasks and Dataview queries

### ISSUE THREAD

**Issue by AngelusDomini** [shap-po/obsidian-party#3]
With the option to have the confetti and sparkle effects on checkboxes, including ones from Tasks and Dataview task queries, would it be possible, as another option, to only have the effects work on Tasks and Dataview queries as opposed to having it work for all checkboxes?

I can see this plugin being helpful when checking my tasks from the Tasks plugin query as a “pat in the back” reward. On the other hand, if all of the other checkboxes in my vault have the same effects when checked, it doesn’t quite make checking Tasks and Dataview queries that special compared to these other, normal checkboxes.

Also, even though I’m asking for the effects to only work on both Tasks and Dataview queries, I don’t use the Dataview tasks queries that often, and when I do, they’re usually not “task” checkboxes like the ones from the Tasks plugin. Thus, it would be great to have two toggles for this: one for having the effects only on Tasks queries, and the other for having the effects only on Dataview task queries, and where having both toggled on would have the effects work on both Tasks and Dataview queries but not on other checkboxes.

Hope I’m making sense lol

**Comment by shap-po** [comment]
Hello! That sounds like a good idea, I'll see what I can do.

**Comment by shap-po** [comment]
Sorry for the long wait. I hope you'll like the new update :D

**Comment by AngelusDomini** [comment]
And I’m sorry for taking this long to thank you. Thanks for this update!

**Comment by shap-po** [comment]
If you have any other suggestions, I'd be happy to add them in the next updates
