### ISSUE TITLE
[Bug] Obsidian window not moveable after clicking checkbox

### ISSUE THREAD

**Issue by flex-chillrsn** [shap-po/obsidian-party#4]
After finding this issue was occuring while running a custom theme and multiple plugins, I disabled all plugins and reverted to the default theme. When I enabled obsidian-party as the sole plugin, I found that anytime I clicked a checkbox complete, and the animation played, I would no longer have control of the window. This consistently happened each time I tried it. Running Obsidian on Windows 10.

**Comment by shap-po** [comment]
Thank you for letting me know. I will fix it in a day or two

**Comment by shap-po** [comment]
Okay, it should work properly now 🎉
