### ISSUE TITLE
Kanban Compatability

### ISSUE THREAD

**Issue by flex-chillrsn** [shap-po/obsidian-party#6]
Hello! This is somewhere between a feature request and a question: 

I'd love to get this plugin to work with the Obsidian Kanban plugin (I've requested this as a feature over on their Issues board but never got any response/feedback). 

The idea would be to have a party animation play on a card when the card is moved to a section where cards are marked as complete. Is this something that is possible? As a CSS snippet or otherwise? I like to use Obsidian Kanban for managing my tasks/to-dos and this would really add a fun layer to my workflow. Any help to make this happen would be super appreciated.

**Comment by shap-po** [comment]
Hello! I love this idea, and I'll see what can I do about it. Unfortunately, I don't have much time right now, so please, don't expect me to finish it quickly.

**Comment by flex-chillrsn** [comment]
Not a problem! Thank you for your consideration, and hope to see it in a future release.

**Comment by shap-po** [comment]
It took me far less time than I expected, but it seems to be working! 🎉

**Comment by flex-chillrsn** [comment]
Awesome! Can't wait to incorporate this. Cheers!
