### ISSUE TITLE
Not working in Obsidian 1.1.9

### ISSUE THREAD

**Issue by leongieser** [shap-po/obsidian-party#7]
Default Theme

installed plugins
- Admotion
- Advanced Tables
- Code Emitter
- Excalidraw
- File Color
- Homepage
- Obsidian_to_Anki
- Party

**Comment by shap-po** [comment]
Hello! Thanks for reporting this issue and pinning installed plugins.
I've installed all of them on a fresh vault and the plugin seems working perfectly fine. Do you have any error logs in the console? What's your OS? What type of checkboxes are you using (`+` or `-` ones)? Also, it might be helpful to pin the config file of `obsidian-party`.
I'd be glad to resolve this issue! 🎉

**Comment by leongieser** [comment]
Oh sorry - should have added that in the first place
There is no output in the console when pressing the button with confetti or sparkles class

i am on win 11 pro 22H2

does not work either on macbook air m1 Ventura 13.0

did i miss something during the setup? i tried both building from this repo and adding it via community plugins

**Comment by shap-po** [comment]
Oh, I almost forgot that button feature even existed... But it still works fine for me on win11 and Ubuntu, just copied button from the documentation `<button class="confetti">Click me!</button>` :thinking: 
The installation process requires only to install & enable the plugin 
Do checkboxes work for you?

**Comment by shap-po** [comment]
Theoretically, the effect might not be triggered if you are using editing mode, but reading mode should be fine

**Comment by leongieser** [comment]
Well the good news is that i got it to work on the macbook now. i may have forgotten to reload the plugins after disabling them but no luck on windows - no console output on checkboxes either.
