### ISSUE TITLE
Feature Request - Add confetti sound option

### ISSUE THREAD

**Issue by WritwikRay** [shap-po/obsidian-party#9]
Awesome plugin! Love the work. Could you add a sound effect to the button! I get majority users will not like the idea but some of us will. Also if you do, making an option for custom sounds will be great. Thanks for the awesome plugin btw.

**Comment by yasd251** [comment]
Hey @WritwikRay, if you are still looking for a plugin that has sounds, you can check out a one I made for any checkboxes! its called "Checkbox Sounds" on Obsidian

You can see the repo [here](https://github.com/yasd251/checkbox-sounds-plugin)

**Comment by shap-po** [comment]
I apologize for the delayed response to your feature request. Unfortunately, I haven't been able to maintain this project as actively as I'd like.

@yasd251, thank you for providing a solution with your plugin, I'll make sure to check it out.

I'll close this issue as not planned, thank you for your understanding.
